### ISSUE TITLE
UDP port is not opening properly in 4.12b-gecda7 and a small feature request.

### ISSUE THREAD

**Issue by 4C3T** [airdcpp/airdcpp-windows#71]
Running VPN, and I seem to have trouble getting the client to open the UDP port. My VPN ISP allows me to open specific ports. Usually I use TCP/UDP ports, and even (not that it would matter) if I open an UDP port it still doesn't open it.
It would also be nice to have some text in the settings that explained what the ports are used for exactly, just something short & concise right next to the input fields.
Sometimes the other ports seem to stop working, and I'm not sure if it's my computer that's on the fritz (been having problems lately with Windows), or if it is in fact the client that's stirring the pot. But, I usually cycle the ports which seems to be working and I'm still not sure which port is for searches, transfers and other communication. That's why it would be nice to see which one's what.

I hope this problem lies with the client and not my computer/VPN. I should also point out that I run other clients, and their ports are working just fine. I also use WireGuard so the ports are locked via keys to the client VPN software.

**Comment by Sopor** [comment]
The UDP port is used for searches.

Use ports in this range 49152–65535 because they are private ports that cannot be registered with IANA.

There are the same amount of TCP ports as UDP ports, so you can use the same port number for TCP as for UDP, but you need to open a second TCP port for TLS.

You can of course use another UDP port, but one problem with UDP is that you can't test the port to see if it is open as you can do with TCP.

So, if you go to a port tester site `https://portchecker.co` and you get `Port 52345 is open` it is most likely that even the UDP port 52345 is working.

I don't think there is a problem with AirDC. It is mostly your VPN setup or a firewall issue.

**Comment by 4C3T** [comment]
Ok. Thanks for the clarification.
But it would also be nice if this could be explained in the settings as well. Would  be nice to know for some people. Just the other day I said that three ports were required to another person, and now I need to retract that statement =0/

I haven't had any trouble now for a couple of days, and I did have some earlier, but I was unsure whether it was the client/OS that wasn't seeing eye to eye quite there (Windows 19 Server), as I did initially have some connectivity issues (F/W disabled since installation), but it settled and it did look like I got all the kinks out. Did have some issues with the VPN client, but updated it (and other software too) and the problem went away.

Then it was this problem at times when I had to cycle the ports since one closed after a while. Unsure when, what and why as I don't use the search much, and for the most part transfers are idling empty, but at times I get a lot of uploads.
Usually when I swapped the ports I could see traffic increasing and I also sometimes check with a port scanner to see, and I've found that TLS port closed a couple of times (I assume that's used for encrypted traffic like chats and such ADC stuff?) but I haven't investigated any further than that.

Anyway, at those times, I've swapped around the ports and got the transfers working again.
Usually, I discovered this problem when searching, or trying to download a file list/files and gotten timeouts.
Meanwhile, other client software didn't have the same problem, so that's why I suspected AirDC as the culprit.

**Comment by Sopor** [comment]
Some VPN providers offers static IP address that make all ports open (you need to pay extra for it). Is that what you have?

If you don't have that you need to share all the ports with other users and i assume you can easy lose your ports if you share them.

I'm asking because you wrote _`allows me to open specific ports`_, so i assume you can't use all the 65535 ports?

**Comment by 4C3T** [comment]
Yeah, I do have that option, but not on that computer I'm running DC on.

Don't know if these are shared with others, but I can't say that I've seen anything about that on the VPN ISP's site.

And, yes, I have somewhat limited port range, somewhere in the neighborhood of between 4xxxx and up, guessing 5 or maybe 6xxxx. Haven't investigated any further on that. I think a message will display if outside the scope, but it's been literary years since I last tried to open any above/below. I can't check now either 'cos I'm using all of them and I can't open more than 7.

**Comment by 4C3T** [comment]
So, it's been working solid for over a week now, and I found the culprit to my BSODs - SpeedFan. Every time I started it (It doesn't auto-start) a few/many hours later it crashes. It does report some errors when trying to read some addresses, and sometimes freezes for either a while or permanent so a restart of the app is necessary. But I've never had this problem before with a BSOD because of it. But, then again, every computer is different, and this being an AMD 2x16 core server... Perhaps not so strange.

So, I see myself out with this comment.
Devs: Thanks for a nice client, keep up the good work!
