### ISSUE TITLE
Unable to download large (1GB+) user filelists

### ISSUE THREAD

**Issue by ryehamstrawberry** [airdcpp/airdcpp-windows#74]
As the title indicates, there are some users with huge file lists that cannot be viewed in their entirety via "View file list" and only partially via "Browse file list", which also prevents using Clean ADL Search with said file lists.

I'm unsure what the maximum size threshold is before AirDC++ will not process the request, but I know it occurs for lists of size 1GB+ (200TB share, 30 million files that are likely NFOs, etc.).

From reports I have received, this affects users of v4.11 and v4.12b.

While I'm sure this is a unique situation, it would be nice to be addressed if there's a possible fix for it.

**Comment by maksis** [comment]
This is an intentional feature that was added in version 3.70: https://github.com/airdcpp/airdcpp-windows/blob/8fe9db32a4ef6c57b9c61e8def9d63d8fd0c5be5/Changelog_AirDC.txt#L100

Note that 1 GB is the compressed size of the filelist and the actual uncompressed list is much larger. Handling such large filelists is problematic in many ways (and a huge waste of resources). 

ADL search is a legacy feature and AirDC++ provides a scripting API that could be used to implement checks similar to ADL search with minimal resource consumption.
