### ISSUE TITLE
I keep getting disconnected with the message: *** an existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by davelev74** [airdcpp/airdcpp-windows#82]
I keep getting disconnected with the message: *** an existing connection was forcibly closed by the remote host
I am on Windows 10 This was happening as soon as I upgraded to the newest DC++ version so I switched to AirDC++ and it is still a problem.

![Systen_Info](https://user-images.githubusercontent.com/44758292/206936887-de20047d-5fc8-44dd-9d27-242741718e08.PNG)

**Comment by Sopor** [comment]
That has nothing to do with either AirDC++ or DC++. Something in you network is causing this.

Could be a firewall, router, anti virus software or even your ISP ...

Are you using a wireless connection, try using a cable instead or try other cables.

I don't know what connection you are using, but connect your computer directly in the CPE and try without your router.

**Comment by RoLex** [comment]
Another cause of this issue could be that your client is trying to connect to same hub twice - like having same hub in favourites registered twice. It could be two different addresses, but still pointing to same hub with same nick. Please provide some logs inclusive hub address. Also you can include a screenshot with a list of hubs you are connected to. This is a common issue today, because many hubs have merged together during past years. Please respond if you are interested, else this issue will be closed soon.
